version: "3"

services:
  app:
    container_name: atcoder

    image: atcoder

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./app/:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro

    stdin_open: true
    tty: true
